name: r_tree
version: 1.1.2
description: R-tree implementation to index and query two-dimensional data
homepage: https://github.com/Workiva/r_tree

environment:
  sdk: '>=2.11.0 <3.0.0'

dev_dependencies:
  benchmark_harness: any
  build_runner: '>=1.7.1 <3.0.0'
  build_test: ^0.10.9
  build_web_compilers: ^2.12.0
  dart_dev: ^3.0.0
  dart_style: '>=1.3.1 <3.0.0'
  dependency_validator: ^2.0.0
  meta: ">=1.2.2 <1.7.0"
  test: ^1.15.7

dependency_validator: 
    ignore:
      - meta
